### ISSUE TITLE
Introduce job_id vacancy field

### ISSUE THREAD

**Issue by mighty-mhsl** [fakng-agrgtr/fakng-agrgtr#33]
It will help to ensure that we don't send notifications about the same vacancy twice.

Usually, all vacancies on the companies' sites have their specific identifier. It's worth storing it separately so that later we can base notification history information on this.

Also all parsers should be updated accordingly to take this new field into consideration.

**Comment by alekseiiagnenkov** [comment]
Сan't we track it with the vacancy id?

**Comment by mighty-mhsl** [comment]
Vacancy_id is our internal id for storing entities in DB. This is just our primary key. But different sites has their own job_ids. So better to have it separately
